version: '3.5'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: ${POSTGRES_DATABASE:-database}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge
