version: '3.5'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-passwd}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-database}
    volumes:
      - mongo:/data/db
    networks:
      - mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-passwd}
    networks:
      - mongo
    depends_on:
      - mongo

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: ${POSTGRES_DATABASE:-database}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    depends_on:
      - postgres

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "${REDIS_COMMANDER_PORT:-8082}:8081"
    environment:
      REDIS_HOSTS: local:redis:${REDIS_PORT}
    networks:
      - redis
    depends_on:
      - redis

volumes:
  mongo:
  postgres:
  pgadmin:

networks:
  mongo:
    driver: bridge
  postgres:
    driver: bridge
  redis:
    driver: bridge
